### ISSUE TITLE
issue with option "Reload window Manager"

### ISSUE THREAD

**Issue by tele1** [kozec/fusion-icon-gtk3#1] opened 2015-05-08 13:08 UTC
I see issue inside fusion-icon,
when I click "Reload window Manager" this freeze menu bar,
if I have open window, I can minimize window and this defrosting menu bar.
The same I have when I run compiz before  fusion-icon.

http://www.paste.org/78284

> [gg@localhost ~]$ fusion-icon
> - Detected Session: 05MATE
> - Searching for installed applications...
>   compizconfig - Error: error occurred during scandir: No such file or directory
>   compizconfig - Info: Backend     : ini
>   compizconfig - Info: Integration : true
>   compizconfig - Info: Profile     : default
> - NVIDIA on Xorg detected, exporting: __GL_YIELD=NOTHING
>   /usr/lib/python2.7/site-packages/FusionIcon/interface_gtk3/main.py:34: Warning: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
>   item.set_image(Gtk.Image.new_from_stock('gtk-preferences', Gtk.IconSize.MENU))
>   /usr/lib/python2.7/site-packages/FusionIcon/interface_gtk3/main.py:86: Warning: The property GtkImageMenuItem:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
>   item = Gtk.ImageMenuItem.new_from_stock(Gtk.STOCK_QUIT)
>   /usr/lib/python2.7/site-packages/FusionIcon/interface_gtk3/main.py:86: Warning: The property GtkImageMenuItem:accel-group is deprecated and shouldn't be used anymore. It will be removed in a future version.
>   item = Gtk.ImageMenuItem.new_from_stock(Gtk.STOCK_QUIT)
> - Starting Compiz
>   ... executing: compiz --replace ccp
>   compiz (core) - Info: Loading plugin: core
>   compiz (core) - Info: Starting plugin: core
>   compiz (core) - Info: Loading plugin: ccp
>   compiz (core) - Info: Starting plugin: ccp
>   compizconfig - Error: error occurred during scandir: No such file or directory
>   compizconfig - Info: Backend     : ini
>   compizconfig - Info: Integration : true
>   compizconfig - Info: Profile     : default
>   compiz (core) - Info: Loading plugin: composite
>   compiz (core) - Info: Starting plugin: composite
>   compiz (core) - Info: Loading plugin: opengl
>   compiz (core) - Info: Starting plugin: opengl
>   Compiz (opengl) - Info: GLX_EXT_buffer_age is supported
>   compiz (core) - Info: Loading plugin: copytex
>   compiz (core) - Info: Starting plugin: copytex
>   compiz (core) - Info: Loading plugin: compiztoolbox
>   compiz (core) - Info: Starting plugin: compiztoolbox
>   compiz (core) - Info: Loading plugin: decor
>   compiz (core) - Info: Starting plugin: decor
>   compiz (core) - Info: Loading plugin: annotate
>   compiz (core) - Info: Starting plugin: annotate
>   compiz (core) - Info: Loading plugin: move
>   compiz (core) - Info: Starting plugin: move
>   compiz (core) - Info: Loading plugin: resize
>   compiz (core) - Info: Starting plugin: resize
>   compiz (core) - Info: Loading plugin: matecompat
>   compiz (core) - Info: Starting plugin: matecompat
>   compiz (core) - Info: Loading plugin: place
>   compiz (core) - Info: Starting plugin: place
>   compiz (core) - Info: Loading plugin: wobbly
>   compiz (core) - Info: Starting plugin: wobbly
>   compiz (core) - Info: Loading plugin: fade
>   compiz (core) - Info: Starting plugin: fade
>   compiz (core) - Info: Loading plugin: cube
>   compiz (core) - Info: Starting plugin: cube
>   compiz (core) - Info: Loading plugin: rotate
>   compiz (core) - Info: Starting plugin: rotate
>   compiz (core) - Info: Loading plugin: gears
>   compiz (core) - Info: Starting plugin: gears
>   compiz (core) - Info: Loading plugin: switcher
>   compiz (core) - Info: Starting plugin: switcher
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: No default decoration found, placement will not be correct
>   compiz (decor) - Warn: No default decoration found, placement will not be correct
>   compiz (decor) - Warn: No default decoration found, placement will not be correct
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: failed to bind pixmap to texture
>   compiz (decor) - Warn: No default decoration found, placement will not be correct
>   compiz (decor) - Warn: No default decoration found, placement will not be correct
>   compiz (decor) - Warn: No default decoration found, placement will not be correct

System: PCLinuxOS 64bit MATE
Compiz 0.9.12.1

**Comment by kozec** [comment] 2015-05-08 18:10
Restart option only calls `compiz --replace`, so my best guess is bug in compiz / compiz not liking when window disappears while it's starting. Probably small timeout before `compiz --replace` is executed would help?

**Comment by tele1** [comment] 2015-05-08 20:27
> compiz --replace 

when I paste this command this help , but Emerald window decoration disappears,
and taskbar is on top, in default I have task bar below,
When I click task bar, this appears at the bottom, where should.
Probably you have right about issue, when I changed window decoration from 
"Compiz" to "Kwin" issue not exist.
I also tried use emerald but when task bar (menu bar) is frozen, emerald also not working,
but compiz works.

> Probably small timeout before compiz --replace is executed would help?

How can I add bigger timeout ?

Other thing.
Mate use in default Marco window decoration, I hope someday someone can add this to fusion-icon.
I see this in Mint pictures, but I don't know where look source code or paths
http://linuxmint.com/pictures/screenshots/rebecca/mintdesktop.png

picture in "4. Set Window Manager"
http://www.distrogeeks.com/install-compiz-mint-linux/

I will try write on mate forum, maybe someone can help

Edit:
When menu bar is frozen on  bottom, menu bar working for a moment from top,
but I don't see on top, issue not exist when menu bar exist on top.
I try compile compiz.

**Comment by kozec** [comment] 2015-05-10 20:01
Are you able to test code from [this branch](https://github.com/kozec/fusion-icon-gtk3/tree/timeout) ?

**Comment by tele1** [comment] 2015-05-11 01:19
- From this branch I don't see changes,  
  ( I have invisible at the top of the bar which disappears when I click )
  ( maybe now I have new Metacity window manager, but I 'm not sure )
- I wrote on mate forum
  http://forums.mate-desktop.org/viewtopic.php?f=2&t=3566

and on website  exist  " fusion-icon_add_marco.patch "
http://pkgs.fedoraproject.org/cgit/fusion-icon.git/tree/
This path add " Marco " window manager to menu fusion-icon.
Marco window manager use Mate like KWin use KDE.
Can you check and improve , add this patch ?

Thanks ! :-)

**Comment by kozec** [comment] 2015-05-11 06:25
What I mean to test is issue with reloading compiz. Marco support was oneliner and I commited it directly to master branch - f0a601c25268248a5e9b4a60c995682c5b6e6115

**Comment by tele1** [comment] 2015-05-12 13:46
Textar from pclinux forum found workaround for issue with mate-panel ( menu bar ).

> killall mate-panel

this command reload all panels inside Mate,
this working with Compiz, Kwin, Metacity, Marco
I tested also on Fedora 21 64bit Mate in virtualbox,
however in Fedora with mate-panel issue not exist. 
Can you add this to "Reload window Manager" inside fusion-icon to test ?

**Comment by kozec** [comment] 2015-05-12 18:00
You want to kill mate-panel every time when window manager is reloaded? Can I have link to that pclinux forum?

**Comment by tele1** [comment] 2015-05-12 18:22
Yes ( or can be reloaded when only compiz is reloaded ) 

http://www.pclinuxos.com/forum/index.php/topic,132299.15.html

or build path, or write what we need change, we add this only for PCLinuxOS.

**Comment by kozec** [comment] 2015-05-13 06:09
Ok, I think I understand... I'll try to add killing mate-panel when compiz is reloaded as option to "compiz options" menu.

Just to check, does same thing happens even if you are switching from some other WM to compiz, or just when compiz is being restarted?

**Comment by tele1** [comment] 2015-05-13 08:30
Does not matter how, I tested with Compiz, Kwin, Metacity, Marco and this command restart mate-panel
if someone have other desktop environment, mate-panel not exist, so if command exist,
will do nothing.

**Comment by kozec** [comment] 2015-05-13 08:58
This is command to **kill** mate-panel, not to restart it. On Mate, season manager will relaunch it, thinking that it crashed, but on any other environment that uses mate-panel, this command will simply make all panels disappear and possibly render environment unusable.

Anyway, what I need to know is if `killall mate-panel` should be called only when _reload window manager_ option is clicked and compiz is active, or every time no matter which window manager is used, or every time when compiz is starting, not only if it is restarted or launched first time.

It should go without saying that its not bug in fusion icon. What we are doing is workaround and problem should be reported to whoever is developing mate-panel right now. On related note, I tried to replicate problem on Arch Linux and it didn't occurred, so it may be problem specific to PC Linux, caused by some of their patches.

**Comment by tele1** [comment] 2015-05-13 10:08
Yes I know, however now I see " mate-panel --replace "   option will safer .

> $ mate-panel --help
> Usage:
>  mate-panel [OPTION…] 
> 
> Help Options:
>  -h, --help                      Show help options
>  --help-all                      Show all help options
>  --help-sm-client                Show session management options
>  --help-gtk                      Show GTK+ Options
> 
> Application Options:
>  --replace                       Replace a currently-running panel
>  --reset                         Reset the panel configuration to default
>  --run-dialog                    Execute the run dialogue
>  --layout                        Set the default panel layout
>  --display=DISPLAY               X display to use

<

> mate-panel --replace  

  mate-panel --replace ,  will be better and also working, but I don't know check if Mate running,
to run this command, inside other desktop environment will maybe error because command not exist.

>  ... should be called only when reload window manager option is clicked and compiz is active, or every time no matter which window manager is used ...

Should be reload for all window manager, because this is " Reload Window Manager "
- better way to debug if this will not working
- however more important is how you can do.

> It should go without saying that its not bug in fusion icon.

Yes, this is not bug in fusion-icon , mate-panel --replace is only  workaround for issue in PCLinuxOS,
( maybe with compiz , maybe with mate, I don't know now yet )
I say also, you don't need update source code, but build new test source or patch for PCLinuxOS,
we add this patch only for PCLinuxOS, however I need help, because I don't know where change.

**Comment by tele1** [comment] 2015-05-14 05:50
Textar found this for Mint for Mate
https://github.com/linuxmint/mintdesktop/blob/master/usr/bin/mate-panel-compiz-restart#L3

**Comment by texstar** [comment] 2015-05-14 08:28
I'm not sure why mate panel wants to lock on Windows Reload Manager up but my quick and dirty fix for it is to add a one line code to /usr/lib/python2.7/site-packages/FusionIcon/interface_gtk3/main.py

def reload_activate(self, widget):
      wms.restart()
      os.system("killall mate-panel")

**Comment by kozec** [comment] 2015-05-16 14:36
Ok, I added checkbox to "compiz options" submenu that calls "mate-panel --replace" whenever is compiz started.
It would be nice if someone can test if it works beside my own pc :)

Only problem is that it adds dependency on python-psutil package, but I can make it optional later.

**Comment by tele1** [comment] 2015-05-16 22:43
Kozec 
- not working, and I don't know why :-( 
-  I see new option in menu fusion-icon and I checked.
- I don't see something new in terminal output
- I have problem load icon fusion-icon from compiz

When I use "Reload" this --replace output  to other process,  maybe good idea will save all data to file, but this log must be saved from fusion-icon.

However path Textar working very well, except "Compiz Options"
this looks like  not use "def reload_activate" to "compiz --replace options "
For me this path can stay for now, and we try find error in compiz,
or we try build path also for "Compiz Options".
Thanks for help. :)

**Comment by kozec** [comment] 2015-05-17 06:21
No output at all? Not even something like

```
 * Reloading compiz
 ... executing: compiz --replace ccp
 * Reloading mate-panel
```

?
Maybe panel reloads before compiz, in which cause, killall may be better option :(

> I have problem load icon fusion-icon from compiz

I'm not sure if I understand, what kind of problem?

**Comment by tele1** [comment] 2015-05-17 08:02
``` bash
$ fusion-icon
 * Detected Session: 05MATE
 * Searching for installed applications...
compizconfig - Error: error occurred during scandir: No such file or directory
compizconfig - Info: Backend     : ini
compizconfig - Info: Integration : true
compizconfig - Info: Profile     : default
 * NVIDIA on Xorg detected, exporting: __GL_YIELD=NOTHING
 * Starting Compiz
 ... executing: compiz --replace ccp
Traceback (most recent call last):
  File "/usr/bin/fusion-icon", line 58, in <module>
    import FusionIcon.interface_gtk3
  File "/usr/lib/python2.7/site-packages/FusionIcon/interface_gtk3/__init__.py", line 3, in <module>
    import main
  File "/usr/lib/python2.7/site-packages/FusionIcon/interface_gtk3/main.py", line 198, in <module>
    init()
  File "/usr/lib/python2.7/site-packages/FusionIcon/start.py", line 34, in init
    wms.start()
  File "/usr/lib/python2.7/site-packages/FusionIcon/util.py", line 184, in start
    if [ p for p in psutil.process_iter() if p.name() == "mate-panel" ]:
TypeError: 'str' object is not callable
compiz (core) - Info: Loading plugin: core
compiz (core) - Info: Starting plugin: core
[gg@localhost noarch]$ compiz (core) - Info: Loading plugin: ccp
compiz (core) - Info: Starting plugin: ccp
compizconfig - Error: error occurred during scandir: No such file or directory
compizconfig - Info: Backend     : ini
compizconfig - Info: Integration : true
compizconfig - Info: Profile     : default
compiz (core) - Info: Loading plugin: composite
compiz (core) - Info: Starting plugin: composite
compiz (core) - Info: Loading plugin: opengl
compiz (core) - Info: Starting plugin: opengl
Compiz (opengl) - Info: GLX_EXT_buffer_age is supported
compiz (core) - Info: Loading plugin: crashhandler
compiz (core) - Info: Starting plugin: crashhandler
compiz (core) - Info: Loading plugin: compiztoolbox
compiz (core) - Info: Starting plugin: compiztoolbox
compiz (core) - Info: Loading plugin: decor
compiz (core) - Info: Starting plugin: decor
compiz (core) - Info: Loading plugin: annotate
compiz (core) - Info: Starting plugin: annotate
compiz (core) - Info: Loading plugin: move
compiz (core) - Info: Starting plugin: move
compiz (core) - Info: Loading plugin: resize
compiz (core) - Info: Starting plugin: resize
compiz (core) - Info: Loading plugin: matecompat
compiz (core) - Info: Starting plugin: matecompat
compiz (core) - Info: Loading plugin: place
compiz (core) - Info: Starting plugin: place
compiz (core) - Info: Loading plugin: wobbly
compiz (core) - Info: Starting plugin: wobbly
compiz (core) - Info: Loading plugin: fade
compiz (core) - Info: Starting plugin: fade
compiz (core) - Info: Loading plugin: cube
compiz (core) - Info: Starting plugin: cube
Window manager warning: Failed to load theme "Adwaita": Failed to find a valid file for theme Adwaita

compiz (core) - Info: Loading plugin: rotate
compiz (core) - Info: Starting plugin: rotate
compiz (core) - Info: Loading plugin: switcher
compiz (core) - Info: Starting plugin: switcher
```
- from " $ python setup.py build " I don't see errors.
- I mean when compiz is active, I don't have fusion icon on mate-panel in tray.
  Maybe because error " \* Starting Compiz
  ... executing: compiz --replace ccp " is before load icon.
- I tried also run compiz with Adwaita, but only warning about theme disappears.

When I changed int() to str() icon load but not fixed

``` bash
File "/usr/lib/python2.7/site-packages/FusionIcon/util.py", line 184, in start
    if [ p for p in psutil.process_str() if p.name() == "mate-panel" ]:
AttributeError: 'module' object has no attribute 'process_str'
```

**Comment by kozec** [comment] 2015-05-17 10:46
Ok, so pclinux uses horribly outdated version of python-psutil. Good to know :D

\/ This should fix it.

**Comment by tele1** [comment] 2015-05-17 22:31
Working very well for me now :D  Thanks !
( with old python-psutil and with new python-psutil (probably Textar updated))

**Comment by tele1** [comment] 2015-05-18 08:39
/home/. . . /.config/compiz/fusion-icon    <-- Only 1 method exist from this file to run 
"Reload mate-panel ... " in default,  for first run ?
For first run, I mean, when fusion-icon just installed and file ~/.config/compiz/fusion-icon 
not exist yet.

I thing now, if user create new user account, config file will default,
but maybe we can 
- add config file for user, which installed fusion-icon
- and for skeleton, when will user account created, created before config file will be added.
  But if this is also possible change False to True (in default) in code fusion-icon this will also good idea,
  because in PCLinuxOS fusion-icon will default for mate.

**Comment by tele1** [comment] 2015-05-18 09:47
Ok , I found option in util.py

``` bash
        for option in options:
            self.set('compiz options', option, 'False')
        self.set('window manager', 'active wm', 'compiz')
```

And I changed from **False** to **True**

**Comment by kozec** [comment] 2015-05-18 11:16
AFAIK, this bug is present only in PCLinux so far, so if there is need to have option on by default, it may be better to do it as distribution/packaging specific patch. That way is also possible to add default configuration to `/etc/skel`.

It may break stuff for everyone else otherwise - for example, I noticed that pidgin is acting funny when panel with tray icons area gets reloaded. Also, anything that runs from wine will create it's own window with tray icon if tray host disappears.

---

Anyway, did I understood correctly that main problem is solved? If yes, I can add that check if python-psutil is available and merge everything to main branch.

**Comment by tele1** [comment] 2015-05-18 11:22
Solved :-)

**Comment by kozec** [comment] 2015-05-19 22:24
Merged.

**Closed as completed by kozec** 2015-05-19 22:24 UTC
